dist: xenial
language: python

python:
  - "3.6.5"
  - "3.7.9"
  - "3.8.9"
  - "3.9.4"
  - "pypy"

install:
  - pip list & pip install -U setuptools && pip install -U tox-travis

script:
  - tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
