name: cookiecutter-djangopackage CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install Dependencies
      run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt
    - name: Install tox
      run: python -m pip install --upgrade codecov tox tox-py
    - name: Test with tox
      run: tox --py current
    # steps:
    # - uses: actions/checkout@v2
    # - name: Set up Python
    #   uses: actions/setup-python@v2
    # - name: Install Dependencies
    #   run: |
    #         python -m pip install --upgrade pip
    #         pip install -r requirements_dev.txt
    # - name: Test with pytest
    #   run: py.test
